CREATE OR REPLACE FUNCTION SNOWGRAM_DB.CORE.COMPOSE_DIAGRAM_FROM_TEMPLATE("TEMPLATE_ID_PARAM" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Retrieves a complete end-to-end architecture template.\n\n**WHEN TO USE:**\n- User asks for a complete solution architecture\n- User describes an end-to-end use case (Medallion, IoT pipeline, Data Warehouse, etc.)\n- Need a production-ready reference architecture\n- Keywords: \"medallion\", \"bronze silver gold\", \"lakehouse\", \"BI workload\", \"IoT\", \"data mesh\"\n\n**WHEN NOT TO USE:**\n- User wants just a portion/pattern (use COMPOSE_DIAGRAM_FROM_PATTERN)\n- User is building a custom diagram piece by piece (use GENERATE_MERMAID_FROM_COMPONENTS)\n- User wants to modify an existing diagram (use MERGE_DIAGRAMS)\n\n**PARAMETERS:**\n- template_id_param (VARCHAR): Template ID from ARCHITECTURE_TEMPLATES table\n\n**AVAILABLE TEMPLATES:**\n  - MEDALLION_LAKEHOUSE_SNOWFLAKE_ONLY: Bronze/Silver/Gold lakehouse WITHIN Snowflake only (DEFAULT for medallion)\n  - MEDALLION_LAKEHOUSE: Bronze/Silver/Gold lakehouse with EXTERNAL S3/data lake ingestion\n  - REALTIME_IOT_PIPELINE: End-to-end IoT with Kafka and real-time analytics\n  - BATCH_DATA_WAREHOUSE: Traditional ETL with staging, transformation, reporting\n  - MULTI_CLOUD_DATA_MESH: Cross-cloud architecture with data products\n  - ML_FEATURE_ENGINEERING: Feature engineering and model inference\n  - DATA_GOVERNANCE_COMPLIANCE: Governance with masking and RLS\n\n**KEYWORD MAPPING:**\n- \"medallion\", \"bronze silver gold\", \"lakehouse\", \"BI reporting\" (no external sources mentioned) → MEDALLION_LAKEHOUSE_SNOWFLAKE_ONLY\n- \"medallion\" + \"S3\", \"data lake\", \"external\", \"ingestion\", \"cloud storage\" → MEDALLION_LAKEHOUSE  \n- \"IoT\", \"sensor\", \"streaming dashboard\" → REALTIME_IOT_PIPELINE\n- \"batch\", \"ETL\", \"traditional warehouse\" → BATCH_DATA_WAREHOUSE\n- \"multi-cloud\", \"data mesh\", \"federated\" → MULTI_CLOUD_DATA_MESH\n\n**IMPORTANT:** Default to MEDALLION_LAKEHOUSE_SNOWFLAKE_ONLY for medallion requests unless the user explicitly mentions external data sources like S3, Azure Blob, data lake, or external ingestion.\n\n**RETURNS:**\n- TEXT: Complete Mermaid code for the template with subgraphs, or NULL if not found'
AS '
    SELECT full_mermaid_code
    FROM SNOWGRAM_DB.CORE.ARCHITECTURE_TEMPLATES
    WHERE template_id = template_id_param
    LIMIT 1
';