CREATE OR REPLACE FUNCTION SNOWGRAM_DB.CORE.MAP_COMPONENT("WORD" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS '
  SELECT component_type
  FROM SNOWGRAM_DB.CORE.COMPONENT_SYNONYMS
  WHERE synonym = LOWER(REGEXP_REPLACE(word, ''[^a-zA-Z0-9]'', ''''))
  QUALIFY ROW_NUMBER() OVER (ORDER BY weight DESC) = 1
';